# Generated by Django 5.0.1 on 2024-01-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="folder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
