# Generated by Django 5.0.1 on 2024-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_manager", "0003_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="category",
            field=models.CharField(
                choices=[
                    ("VIDEO", "Video"),
                    ("MUSIC", "Music"),
                    ("IMAGE", "Image"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=5,
            ),
        ),
    ]
